### PR TITLE
Update dependencies to include new fixes

### PR DESCRIPTION
**Pull request by DanMossa**
I wasn't sure what Version to make this. A breaking change is correct in the most technical sense but I'm not sure if this is something we care to do.

### CODE REVIEW

**Comment by Vinzent03** [comment]
Is there a reason for the dart SDK bump? Like is that the min for the flutter SDK 3.0.0?

**Comment by DanMossa** [comment]
@Vinzent03 
I believe so. That's the version of Dart that was released with that Flutter version.

**Comment by Vinzent03** [comment]
Since we keep the old dart version, this pr can be closed, right?

**Comment by DanMossa** [comment]
@Vinzent03 I don't think so. There are other packages being updated.

**Comment by Vinzent03** [comment]
But there are no changes to supabase-dart itself, just updates to our sub libraries. I don't think a release is necessary just to bundle the newest sub libraries versions in a supabase-dart version.

**Comment by DanMossa** [comment]
@Vinzent03 that's fair, but what about new users who are downloading this package? Don't we want them to get the bug fixes from other packages?

And what's negative about making a new release?

**Comment by Vinzent03** [comment]
Unless a version is already specified in `pubspec.lock`, pub always tries to use the latest compatible version within the version constraints defined in `pubspec.yaml`. So a new user already gets the latest versions. See [documentation](https://dart.dev/guides/packages#upgrading-a-dependency).

The only benefit of an update here would be that users don't mistakenly think they are completely up-to-date, because the supabase-dart version is up-to-date, but you should always check transitive dependencies as well via `dart pub outdated`.

**Comment by DanMossa** [comment]
@Vinzent03 I didn't realize this! Thanks!

**Pull request closed without merging**
