### PR TITLE
chore: publish version 0.2.7

### PR DESCRIPTION
**Pull request by dshukertjr**
Updates `postgrest` to the newest version and publish version `0.2.7` of `supabase_dart`.

### CODE REVIEW

**Comment by bdlukaa** [comment]
What do you think of, when upgrading the version of the subpackages, we add a +(number) on the version instead of bumping one number ahead?

**Comment by dshukertjr** [comment]
@bdlukaa 
So in this case it would `0.2.6+1`, correct? 

Quite frankly, I don't really know precisely when you are supposed to use the plus sign in dart package versioning, but could you educate me? 😂 Is it like if it's just a tiny minor change you bump a number after the plus sign?

**Comment by bdlukaa** [comment]
It's usually used on hotfixes. (like Flutter 1.13.4+4). I don't know. Both ways are good, but some day we'll be publishing version 0.11.3 just by upgrading packages!

**Comment by dshukertjr** [comment]
@bdlukaa 
I see! I think that makes sense! This discussion is great! I wanted to get some input on how to version this package!

In my mind, I have something like this, but let me know if there's any where you think should be fixed:

>Basic principal taken from official [Semantic Versioning website](https://semver.org/)
Given a version number MAJOR.MINOR.PATCH+HOTFIX, increment the:

>1. MAJOR version when you make incompatible API changes,
>1. MINOR version when you add functionality in a backwards compatible manner, and
>1. PATCH version when you make backwards compatible bug fixes.
>1. HOTFIX version when you make a hot fix

BTW, I have one ambiguity when it comes to versioning `supabase_dart` and `supabase_flutter`. If let's say we added a new backwards compatible feature to `postgrest` and the MINOR version number has bumped up by 1. Should we bump MINOR version number on `supbase_dart` and `supabase_flutter` as well since the features are tightly linked? This is what I have been doing, but would like to know what you think about it.

**Comment by dshukertjr** [comment]
I think after re-reading the Semantic Versioning website, if the last digit of the version number of underlying libraries (postgrest, gotrue etc...) is incremented, version number of `supabase-dart` should be incremented the same way, but what do you think @bdlukaa ?

**Comment by bdlukaa** [comment]
@dshukertjr it's okay for me!

**Review by bdlukaa — APPROVED** [review]

**Pull request merged**
